### ISSUE TITLE
Can you add a NPM Script for building webpack? 

### ISSUE THREAD

**Issue by Teng104** [klareh/nckupacEMS#1]
I installed the webpack locally, so building webpack is not very convenient for me.

**Comment by klareh** [comment]
Yes, I will add it later.

**Comment by Teng104** [comment]
Thanks!

**Comment by klareh** [comment]
I added scripts to build the frontend code.
type `npm run build` in the frontend folder then you can get the building html and js file in`frontend\dist\`.

**Comment by klareh** [comment]
I added scripts to build the frontend code.
Please type `npm run build` in the frontend folder then you can get the building html and js file in`frontend\dist\`.
